### PR TITLE
Visual fixes in SMSmoke

### PR DESCRIPTION
**Pull request by robertlipe**
@davepl, how about this?

## Contributing requirements

* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by rbergen** [comment]
I wasn't asked to comment but I will anyway: for review purposes I would prefer either an isolated PR for the intended change, or a short description of the purpose of the other changes that are now included.

**Comment by rbergen** [comment]
> It wasn't my intention to bypass or exclude you. 

Ha, no, I should have been clearer. I wasn't complaining about being excluded, I was merely apologizing for stomping into a conversation that Dave and you were clearly already engaged in.

> (I'm not sure that's even totally possible...)

:) No, it isn't.

Anyway, thanks for realigning your branch with main, this is now much easier for me to digest.  
I could merge this on my own accord, but then I'd have to see it running first. This week, that's a task I'll have to leave until the weekend. Which gives @davepl a little more time to come up with his feedback.

**Comment by KeiranHines** [comment]
Thanks @robertlipe. I have a bit of travel coming up over the next two weeks so I likely wont be looking to start any new features till after all of that if not later. Having said that, if anyone else reading this wants to toy around with adding the backend for exposing the settings my branch should handle the UI perfectly fine. If there is feedback on the UI from that I will take a look at it either while I am in transit, or once I am done with travels.

**Comment by rbergen** [comment]
> Maybe that's the problem. Maybe it was supposed to be secret and to him
only.

Based on my 2.5 years of collaboration with him I'd say it can be anything **except** this. :)

I'll do some testing over the weekend (I still have to look at #442 in action also), and then make up my mind. We're not in a flaming rush, but we don't have to let things linger for weeks either.

**Comment by rbergen** [comment]
> so there's some benefit to me branching to 442 (or it just merging) pretty soon, too.

If my testing this weekend doesn't identify any meaningful issues, I'll hit the big green button on #442 this weekend as well.

**Review by rbergen — APPROVED** [review]
@robertlipe I looked at this, and this is such an obvious improvement over the current version that I'll merge it after CI completes. If further tuning is deemed necessary then that can be done as a follow up. 

Thanks for taking care of this!

**Pull request merged**
