### PR TITLE
Fixes and addition of treeset

### PR DESCRIPTION
**Pull request by davepl**
## Description

A number of smaller fixes, a build fix for spectrum, and the addition of the treeset project and a new effect for it
## Contributing requirements

* [X] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [X] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [X] I selected `main` as the target branch.
* [X] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by davepl** [comment]
Whew! Please check my work, I had many merge conflicts that I had to resolve in multiple stages, and I've never been down that road with git before!  It

**Comment by rbergen** [comment]
@davepl I sent you an e-mail about this, earlier today. You forced your way through it in a different way than I suggested, but platformio.ini now seems to be broken because of it. I'll try to fix that now.

**Comment by davepl** [comment]
I’m fixing a header issue right now… I was bit because I have the header locally so it builds.  Sorry to break the build with my merge!  I should have it fixed shortly…

 

*	Dave

**Comment by davepl** [comment]
Sorry, I’m not seeing the earlier email?  But I basically followed the git command line instructions it offers in the merge conflict explanation, and that seemed to get med through it.

 

I never did see a problem in platformio.ini, unless I’m still missing it, but it builds on the Jetson Nano that I just tested…

 

My issue was that there was code that referenced the WiFiManager header file, but didn’t include the project lib correctly.  Since I had the header locally I missed that.  

 

I assume it’s OK to check directly into the MAIN branch when fixing a build break?  Not sure what the protocol is….

 

Thanks

Dave

**Pull request merged**
