### PR TITLE
multichannel fix in main.cpp

### PR DESCRIPTION
**Pull request by stretch911**
## Contributing requirements

* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by stretch911** [comment]
multichannel support in main.cpp was using LEDPIN_0 for every condition > a single channel, thusly assigning every channel to LEDPIN_0. Made appropriate changes and tested on my heltec/atomlight setup.
70905809982__BEE04E29-80E9-4947-B364-E1B121E2C894

**Review by mggates39 — APPROVED** [review]

**Comment by stretch911** [comment]
its if CHANNELS ==1 so if it ==2 then ==1 will not set the pin...
that's why CHANNELS >= 2 sets both PIN0 and PIN1 (not my code...just fixing it )

Sent from [ProtonMail](https://protonmail.com), encrypted email based in Switzerland.

------- Original Message -------

**Comment by stretch911** [comment]
Agree. Didn’t want to question the masters of the code!! lol

**Comment by stretch911** [comment]
It sure did!!! Soon to be umbrella

**Comment by rbergen** [comment]
@stretch911 I haven't yet commented on this so far because I can't test what I'm suggesting for lack of necessary gear. However, if we're going to fix this then I propose we extend the clean-up a little. To be concrete, I'd suggest replacing lines 542 to 586 inclusive in the current main.cpp with something like this:

```c++
        #define ADD_CHANNEL(channel) \
            debugI("Adding %d LEDs to channel %d on FastLED.", g_aptrDevices[channel]->GetLEDCount(), channel); \
            FastLED.addLeds<WS2812B, LED_PIN ## channel, COLOR_ORDER>(g_aptrDevices[channel]->leds, g_aptrDevices[channel]->GetLEDCount()); \
            pinMode(LED_PIN ## channel , OUTPUT);

        #if NUM_CHANNELS >= 1
            ADD_CHANNEL(0);
        #endif

        #if NUM_CHANNELS >= 2
            ADD_CHANNEL(1);
        #endif

        #if NUM_CHANNELS >= 3
            ADD_CHANNEL(2);
        #endif

        #if NUM_CHANNELS >= 4
            ADD_CHANNEL(3);
        #endif

        #if NUM_CHANNELS >= 5
            ADD_CHANNEL(4);
        #endif

        #if NUM_CHANNELS >= 6
            ADD_CHANNEL(5);
        #endif

        #if NUM_CHANNELS >= 7
            ADD_CHANNEL(6);
        #endif

        #if NUM_CHANNELS >= 8
            ADD_CHANNEL(7);
        #endif
```

(For completeness I'll mention that the semicolon at the end of the `ADD_CHANNEL(n)` lines can be dropped. I've kept them in because it looks more "natural" to me, but that's definitely a matter of personal preference.)

Again, I can't test this myself, but I think this is easier to read overall - and decreases the chance of typos once the `ADD_CHANNEL` macro is defined correctly.

**Comment by davepl** [comment]
I like the cleanup idea and approach, but argue if we’re touching this, it should move into a function of LEDStripGFX called HardwareSetup or similar.  No need to have all that code right in setup.

If you make it a virtual function of GFXBase, we can then move the matrix setup into a similar function on LEDMatrixGFX.

**Comment by rbergen** [comment]
I like the idea, but for me that's too impactful to implement without being able to properly test the result. :)

To be honest, I'd love to be able to turn the whole thing into a simple `for` loop regardless of where we put it. It's the `PIN0` to (max) `PIN7` defines that make that impossible at the moment.

**Comment by rbergen** [comment]
@robertlipe You're right it's really the FastLED template parameters that are the problem. Which is what I meant to say but didn't - it was getting late.

I was going to merge @stretch911's fix, until I found what I think is a bug in the resulting code. In line 551 (line number after modification) `g_aptrDevices[1]->leds` is used, where I'm pretty sure that should be `g_aptrDevices[0]->leds`. 
Which is a typical mistake to sneak in when you're looking at a block of repetitive code _with one exception_.
Which made me go through the logic as a whole, and led to me to conclude that:

1. There is no sensible reason why NUM_LEDS == 1 should be an exception in the first place.
2. The debug logging for multi-strand scenarios is absent, while those scenarios benefit most of the logging in question.

Which led to my suggestion.

Dave's idea is a more involved refactor - partly because I think we _should_ refactor for the matrix scenario as well, if we make that move. I'm happy to merge a more pragmatic fix for the issue at hand now, I just suggest we do it in a way that addresses the bug and the two points I just mentioned. It's still the same file, and fundamentally the same code.

**Comment by rbergen** [comment]
> I started to get grumbly because this very kind of thing is the reason I find Arduino the Quickbasic of programming. 

I guess it also depends where you're coming from. I apologize for the digression, but I started programming in MSX BASIC on graphing paper because my parents couldn't afford a computer - this was 36 years ago. My first programs that I could actually run were written in GW BASIC, years later. From that background, QuickBASIC was a revelation ("what, you can COMPILE?!?").

> If the issue blocking the merge is testing, perhaps Stretch911 can give this a round on his affected lamp.

Technically the merge isn't blocked, but I don't trust my own "graphing paper coding" enough to commit it to the main codebase without someone confirming first that it does what I **know** it should.

> As an aside, ATOM_LIGHT is our only configuration that provides for NUM_CHANNELS > 1

I know that's true for now. To state the obvious: we're all aiming to put something in place that doesn't break the second that changes. :)

> What is the expected/approximate ratio of NeightDriver users that use it as an instructable-style project and just build a few projects quite literally from the code vs. the user base using it as an API in some wild and crazy thing they're building and extensively modifying and integrating the code in some way? [...] How about the ratio of strip vs. matrix (and matrix neopixel vs. HUB75 even within "matrix")? [...] What's the actual configuration range? [...] What kind of MCU hardware do we actually try to support here? [...] Should there be a web configuration change to allow GBR vs BGR or the length of a strand or APA1? 

I think these are all good questions... and I wouldn't know how to start answering them. The project came to the point it is at now through a means of "singular organic evolution" for most of the time - Dave actually wrote a Discussion post about that yesterday. Now that it's open source, where the project goes next largely depends on the people willing and able to contribute. The ideas we have available from Dave and the outside world are what we see in issues, discussions and PRs.

I do know that Dave would like the project to be usable by "the general audience" at some point. That would be those with no interest in coding or compiling at all. They'd like to buy hardware "off the shelf", be up in running "in 5 minutes" using a fool-proof wizard, and then apply reasonable configuration using a web interface. I think that over the past 9(?) months we've certainly taken some steps in that direction, but we also know there's still quite a bit of distance to cover before we really reach that point.

In the meantime, the source code is here for all to see and use, so I don't think we'll ever have "issues" with people grabbing it and running with it - as long as they respect the license, of course.

>> The debug logging for multi-strip scenarios is absent, while those scenarios benefit most from the logging in question. 

> I considered that a feature to reduce time spin-waiting the UART on a wall of text. Shows you how we can all look at the same code and have such different reactions to it. :-)

Well, we could bump down the logging level on these lines from "Info" to the as-of-yet unused "Debug", but I'd guess the current level was picked for a reason. Personally, I don't think it's that odd to report once at start up how many LEDs are connected to how many channels, but I acknowledge it's a matter of opinion. 

> Agreed. Better to deliver an actual fix (ATOM_LIGHT users are complaining) now than to keep this blocked on a larger refactor when none of us seem to have the right availability and test gear on hand to tackle it now.

That was my thinking as well. Let's fix something that's now plainly broken in a way that's pragmatic yet responsible, and improve further later. I've opened #343 to make sure we don't forget about the latter part.

**Comment by stretch911** [comment]
happy to do some localized testing! do i need to check out a certain branch or fork?

**Comment by rbergen** [comment]
> happy to do some localized testing! 

Thank you, that's highly appreciated!

> do i need to check out a certain branch or fork?

I've just pushed my suggestion to the `fix-multi-channel` branch in my fork. You can check it out from there: <https://github.com/rbergen/NightDriverStrip/tree/fix-multi-channel>

**Comment by stretch911** [comment]
> > happy to do some localized testing!
> 
> Thank you, that's highly appreciated!
> 
> > do i need to check out a certain branch or fork?
> 
> I've just pushed my suggestion to the `fix-multi-channel` branch in my fork. You can check it out from there: https://github.com/rbergen/NightDriverStrip/tree/fix-multi-channel

i cloned your branch, set up secrets.h, tweaked platformio.ini for atomlight to use esp32_dev, built, then uploaded.
I only have IO pin05 working out of the box, however, in globals.h, atomlight is setup for 4 channels on 5,16,17,18. The same pins i'm using in my prototype. Only channel 5 works...will double check main.cpp for said changes.

**Comment by stretch911** [comment]
i am assuming its: g_aptrDevices[4]
gonna switch these back to 0 i think build and upload.

**Comment by rbergen** [comment]
Well, this is exactly why I want to have my code suggestions tested before merging them. :) 

It is interesting though, as VS Code shows me that the macro references for channel 1, 2 and 3 expand to pins 16, 17 and 18 when I hover my mouse over them. The multi-line `ADD_CHANNEL` macro is actually in your main.cpp, right?

**Comment by stretch911** [comment]
looks like i recloned the main branch...hold please

**Comment by rbergen** [comment]
Yeah, you need to clone my fork (or add it as a remote and fetch) and then checkout the fix-multi-channel branch that's in my fork. 

If that doesn't work out, I can temporarily push things to a branch on the main project (i.e. https://github.com/PlummersSoftwareLLC/NightDriverStrip).

**Comment by stretch911** [comment]
code is working on 3 channels at least!! bubblystars still doesn't work, comets look nice!
IMG_0461

**Comment by rbergen** [comment]
> i still am noob w/ github. thanks for coaching.

Everybody has to go through the learning curve at some point. I did it he hard way, and I'm happy to make the path a little easier for others where I can. 😄
(And please don't think I'm an expert, either...)

Which of the 4 channels isn't working?

**Comment by stretch911** [comment]
bouncing balls may of broke...it's like it bounced once and then a blue pixel on one end of each channel and a white pixel at the other...stay tuned.

**Comment by rbergen** [comment]
Haha, I will. But if I'm honest, I don't see how that could have been caused by the difference between the code changes you were proposing, and those you're testing now. I'll await your further findings!

**Comment by rbergen** [comment]
Thanks for the update. I'm not exactly sure how this translates to an answer to the question if the suggestion I made for enabling multiple strips on multiple pins works or not. Maybe it's still too soon to say.

I'll just wait until you make an unequivocal statement on the matter. :)

**Comment by stretch911** [comment]
> Thanks for the update. I'm not exactly sure how this translates to an answer to the question if the suggestion I made for enabling multiple strips on multiple pins works or not. Maybe it's still too soon to say.
> 
> I'll just wait until you make an unequivocal statement on the matter. :)

if the only thing that changed here was multichannel, that is definitely working... and the code is much cleaner and easier to follow.
i will go back to main branch, and make the update you provided in main.cpp and that way i know its nothing else messing pixel01 and pixel53. I do know bouncing ball was working great prior to flashing w/ your branch. stay tuned.

**Comment by rbergen** [comment]
Sounds like a good approach to me. Let me know when you've come to a conclusion - obviously no rush.

Thanks!

**Comment by stretch911** [comment]
still have figured out Bouncing Balls...i used to get 3 colors, green, red and blue..now i get a blue and a white and they bounce once then stop on the extremes.
the 53 pixel (embarrassed) is actually pixel 54 cause i don't know how to count leds on a strip before i cut them lol. but pixel 1 is not lit on Palet Effect..hmmm...again something i probably didnt notice before.

**Comment by rbergen** [comment]
I'm maintaining my holding pattern. If and when you're convinced my version of the multi-channel code is good, you can just push an update containing it to your fork.

**Comment by rbergen** [comment]
Just to keep things aligned across PRs and issues: I closed #343 in favor of #349 - the latter includes the former.

**Comment by rbergen** [comment]
Closing this, as the proposed change has now been rolled up into #365 that was merged earlier today.

**Pull request closed without merging**
