### PR TITLE
MD Lint config, Wifi Status on heart beat, Fixed ENABLE_WIFI include.

### PR DESCRIPTION
**Pull request by MatthewvanBuuren**
## Description
Nothing special just adding some MD linting config to suppress annoying problem reminders, corrected some simple MD mistakes.
Note: I only added suppress lint rule config to keep most of the existing style where it made sense.

## Contributing requirements
ACK, PR conforms to CONTRIBUTING.md

* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by MatthewvanBuuren** [comment]
Accidentally threw the second commit in for Network, Didn't know Git Pull was doing a fork merge.

**Comment by rbergen** [comment]
Hi @MatthewvanBuuren, I'd like to ask you to please isolate the WiFi related commit from the ones related to Markdown linting, and open a separate PR for it. This will require you to apply the WiFi change to a different branch, created from PlummersSoftwareLLC:main. 
The two updates are totally unrelated, and I'll be transparent about the fact that I'm not sure the changes related to MD linting pass the BlinkenPerBit criterion. I'd like to be able to separately consider and move forward on the WiFi change regardless of that.

**Comment by rbergen** [comment]
I've given the Markdown linting some more thought, and I think we can merge it provided that:

- We don't use general suppression of rules. For the majority of the rules that are now suppressed, the violations should simply be fixed in the Markdown text. I see two exceptions to this: the embedded HTML for the logo, and the no emphasis as heading for the "dated signature" just under the logo. I think these are better addressed using specific `<-- markdownlint-disable-next-line MDnnn -->` comments.
- For the language identifiers that are added to code blocks, we stick to the identifiers included in [Linguist's languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) file.

Just for clarity, I still think separate PRs need to be opened for each of the changes (Markdown linting on the one hand, and WiFi on the other).

**Comment by MatthewvanBuuren** [comment]
👍 Just cleaning up my fork knowing now the working model. Will submit again in the following days.

**Pull request closed without merging**
