### PR TITLE
Merge Dave's fork into PlummersSoftwareLLC

### PR DESCRIPTION
**Pull request by davepl**
## Description
Refactor char * to String, refactor audioanalyzer, clean up includes

## Contributing requirements

* [X] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [X] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [X] I selected `main` as the target branch.
* [X] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Review by rbergen — APPROVED** [review]
LGTM and CI agrees

**Comment by davepl** [comment]
Checking in to fix build break after refactor checkin

**Comment by davepl** [comment]
Thanks… what resets the “failing” on the main page?  The PR passed, so once merged I’d expect it to show success, but apparently not!

- Dave

**Comment by rbergen** [comment]
The merge of the PR itself triggers one more, final, CI run that verifies if the main branche's new codebase passes. That run just completed successfully, so now the main page will indeed show success again.

**Pull request merged**
