### PR TITLE
Bug fix/config dialog

### LINKED ISSUE #504: Web UI: improve rendering of setting editors
While working on #503 I noticed a couple of things that I think we need to improve about the way setting editors are rendered in the global and effect setting dialogs. Specifically:

1. The name/label of a setting now seems to be rendered using the exact same font, including size and color, as the setting description. Particularly with combinations of setting editors that are not textual, this can make it difficult to distinguish one setting from the next. I think the setting names/labels should be made to stand out a little more. Whether this should be done using a bigger font, brighter color, text decorations or something else altogether, I'll leave to someone with actual UI design skills.
2. For Boolean/checkbox settings, the setting description is not shown and as such completely inaccessible. I think we should somehow make the description for these settings visible or accessible also. As with the other point, I'm not sure how to best do this.

### PR DESCRIPTION
**Pull request by KeiranHines**
## Description
Fixes #504. Added descriptions for checkboxes, added padding before input names/titles. Increased font size of titles and made titles consistently ontop of the input.  
image
image

## Contributing requirements
* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by rbergen** [comment]
@KeiranHines Thanks for picking this up. Looking at the "After" picture, I'd like to ask the following concerning the checkbox controls:

1. Could you realign the left edge of the checkbox with the left of the other controls, like in the "Before" picture? The checkboxes seem to have "drifted to the left" and now look out of line.
2. Ideally, I'd like to left-align the description for checkbox controls with the checkbox label. If that requires too much manual pixel-count hacking, then I think we should just left-align it with the other controls/descriptions too.

**Comment by KeiranHines** [comment]
image
Corrected

**Comment by KeiranHines** [comment]
8:53pm. Not that bad. I knew where both issues were cause they were both things that kept needing styling every time I adjusted them for the design ideas posted on the issue discussion.

**Comment by rbergen** [comment]
@KeiranHines Thanks! One more thing I'd like to check: would it be possible to decrease the whitespace between the checkbox/label combo and the description underneath a little bit? If this is just how things align because CSS then don't worry about it.

**Comment by KeiranHines** [comment]
image

**Comment by rbergen** [comment]
@KeiranHines Perfect! Thanks again for the work on this!

**Comment by rbergen** [comment]
Just noting for the record that I updated some of the checkbox setting descriptions to make them a bit less technical, now that they're shown in the UI.

**Comment by KeiranHines** [comment]
No worries. Always happy to contribute. I approve of the new descriptions. I considered making the same change myself.

**Review by rbergen — APPROVED** [review]
LGTM!

**Comment by rbergen** [comment]
@robertlipe Good point, should have seen that myself. I'll include it in an upcoming PR to stop our Improv implementation sending back device URLs for devices that don't have the webserver enabled.

**Comment by rbergen** [comment]
Yeah, that is true. But if I'm honest, in this case it was also "I really, really have to take the dog for a walk now..." :)

**Pull request merged**
