### PR TITLE
Fix StarryNight variables

### PR DESCRIPTION
**Pull request by rbergen**
## Description
This:
- converts the `mult` and `glob` variables that were added in #75 into globals.h `#define`s.
- adds the brooklynroom and ledstrip (#81) configurations to the CI workflow.
- removed the treeset config from CI, based on [a comment on PR #95](https://github.com/PlummersSoftwareLLC/NightDriverStrip/pull/95#issuecomment-980639164).

## Contributing requirements
* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by BeldrothTheGold** [comment]
I'm sorry that I wasn't able to get to this. I wasn't expecting the PR to be merged before I had a chance to make the requested changes.

**Comment by rbergen** [comment]
There's absolutely no need to apologize. A factor was indeed that the PR got merged a bit too early, due to a slight miscommunication between Dave and myself.

**Comment by rbergen** [comment]
Converting to draft due to upcoming merge conflict with #95.

**Comment by rbergen** [comment]
Merging with an out-of-band ok from Dave.

**Pull request merged**
