### PR TITLE
Feature/new weather icons

### PR DESCRIPTION
**Pull request by mggates39**
## Description
Adding a more colorful set of icons for the weather.  Implemented day and night versions.  Fixed an issue in tomorrow's minimum and maximum temperatures.

I have kept this branch up to date with all changes that have been merged into main to ensure no issues with the current code base.

This should close issue [#256](https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/256)

## Contributing requirements
* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by rbergen** [comment]
@mggates39 Could you please try to squash your commits? We're currently looking at 67 of them, which causes disproportionate strain on my scroll finger. :)

**Comment by rbergen** [comment]
@mggates39 That's fine, I'm not trying to argue with your development approach, but the resulting commit trail is a bit much to be practical at this stage.

**Comment by mggates39** [comment]
I see what you mean.  This is a learning experience for me.  I think I see how I can address this with the next feature I do a Pull Request.

**Comment by mggates39** [comment]
@rbergen I have read up on how to squash commits.  If you would decline this PR, I will put up another one tomorrow that is greatly reduced in the number of commits.

Thanks,

**Comment by rbergen** [comment]
@mggates39 Well, we (you) could possibly rewrite history on this PR by force-pushing a squashed version of the commits that are here to your feature branch, but it's probably cleaner not to do that.

If you're willing to reopen the PR with a condensed commit list, then I'd appreciate that.

**Comment by mggates39** [comment]
@rbergen I will do that.  go ahead and close or delete this one and I will get another one up shortly.

**Comment by mggates39** [comment]
@rbergen The new PR is up please retire this one.  Thank you.

**Pull request closed without merging**
