### PR TITLE
Extend SettingSpec

### PR DESCRIPTION
**Pull request by rbergen**
## Description

This extends the `SettingSpec` struct for future use by the web UI. Specifically, it:

- Makes the `EmptyString` property `std::optional`, thereby allowing for a distinction between explicitly not allowed, explicitly allowed, and "we'll silently ignore empty" - as per [this comment](https://github.com/PlummersSoftwareLLC/NightDriverStrip/pull/478#issuecomment-1785353947) on #478.
- Adds a Slider type, which can be used to ask the front-end to use a slider to set a numerical value. This is discussed in [this comment](https://github.com/PlummersSoftwareLLC/NightDriverStrip/issues/479#issuecomment-1790376007) on #479.
- Adds some rudimentary (and optional, because `struct`) logic to finish setting defaults and perform sanity checks on the consistency of properties. If at some point this reaches a higher level of complexity than it currently does then we may need to decide to make the `struct` a `class`; partly because errors in the specs will quickly show up as weird behaviour in the web UI that's easy to relate to oddness in the spec contents, I don't think that's necessary yet.

## Contributing requirements

* [x] I read the contribution guidelines in [CONTRIBUTING.md](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/CONTRIBUTING.md).
* [x] I understand the BlinkenPerBit metric, and maximized it in this PR.
* [x] I selected `main` as the target branch.
* [x] All code herein is subjected to the license terms in [COPYING.txt](http://github.com/PlummersSoftwareLLC/NightDriverStrip/blob/main/COPYING.txt).

### CODE REVIEW

**Comment by KeiranHines** [comment]
@rbergen for the slider type I have a few thoughts. Firstly and probably the most encompassing. Instead of a full new type. Would it make sense to add a metadata property. Similar to the 'emptyString' property for numeric config. Something like a `preferredDisplay` property. On the frontend, I could ingest that and render out different inputs based on that, if its set e.g. 

```
{
   name: 'brightness',
   type: 'integer',
   preferredDisplay: 'slider' 
} 
```
That would clearly say, I want this field to be a slider display not just an numeric input box. Alternatively you could use a `tickSize` property. If the frontend sees that on a numeric field it renders a slider with ticks at the tickSize frequency. This could be useful in cases where you wanted to a numeric input but didn't need the fidelity of every single integer value. 

To add the questions that got me to this point.
1. With the slider input type, will it support integer and floating point at some point. 
2. In the idea for the UI to just render a slider between min/max and allow the user to adjust to any point along that slider, or should there be a config for tickSize or majorTick/minorTick? 
3. Would it be easier to add a `preferredDisplay` `uiDisplay` or similar property as optional for existing datatypes so the input can be configured as say slider, dropdown or other options in the future without having to have a unique type for each one?

**Comment by rbergen** [comment]
I thought about this before making these changes, and I decided against adding a metadata property of the "preferredDisplay" type. The reason is that we would effectively add another dimension to the UI control specification and front-end implementation side, and I think that could make things quite a bit more complicated in the end, for very limited gain if any.

Coming from a different angle one could argue that the setting spec "type" property already _is_ a control selector. At the JSON level, almost all properties are actually a "number". That's even true for the type representing a colour, as you'll soon find. As such, it already is the type that indicates what editor control to apply.

About the underlying type at the C++ side, we could indeed make that a float (or actually, double) instead of an int. I chose an int because as a user I've hardly ever seen sliders that actually slide over a floating point value - where they possibly would, they tend to be sliding over a more discrete derived scale (like a percentage) instead. In fact, IIRC then all OS-provided slider controls I ever worked with back in my desktop app development days worked with integer ranges and values as well.

Concerning ticks and hints for those, I think we can choose to chew that food when we have to, if we ever have to. In the case of the brightness I think we can do without them, for one.

**Comment by KeiranHines** [comment]
Sounds good to me. I will add support for the new slider type in the Ui sometime this week. I assume with the new slider type min/max are required otherwise a slider wouldn't be very functional.

**Comment by rbergen** [comment]
@KeiranHines That's correct. I've even implemented a (rudimentary) check on the presence of both min and max values when a Slider `SettingSpec` is constructed at the back-end.

**Pull request merged**
